version: "3.8"

services:
  app:
    container_name: 3drenders-admin-app
    image: 3drenders-admin
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
