version: 0.0
os: linux
on:
  push:
    branches:
      - main
files:
  - source: /
    #destination: /var/www/html/3dRenders2023/
   destination: /usr/share/nginx/html/3dRenders2023/
    command: ["composer", "install"]

