<ol>
    <li style="text-align: justify; "><strong> INTRODUCTION</strong></li>
</ol>
<p style="text-align: justify; ">La présente politique de cookies (témoins de connexion) s'applique à tout site web (collectivement «&nbsp;site Web&nbsp;») pris en charge par la société Mentor et tous les domaines en lien avec la plateforme Threedrenders, aux termes de la présente politique ou suivant les références y comprises.</p>
<ol start="2">
    <li style="text-align: justify;"><strong><strong> QU'EST-CE QU'UN COOKIE ?</strong></strong></li>
</ol>
<p style="text-align: justify;"><strong><strong>2.1</strong></strong>&nbsp;Nous utilisons des cookies et d'autres technologies afin d'activer des fonctionnalités sur le site Web. Un cookie est un petit fichier de texte qui contient les paramètres Internet. La prochaine fois que vous visiterez ce site Web depuis le même dispositif, le cookie et les informations qu'il contient seront soit renvoyés au site Web d'origine (cookie de première partie) ou à un autre site Web auquel il appartient (cookie tiers). Ce faisant, le site Web pourra détecter qu'il a déjà été ouvert sur ce navigateur, et dans certains cas, il variera alors le contenu qu'il affiche.</p>
<p style="text-align: justify;"><strong><strong>2.2</strong></strong>&nbsp;Presque tous les sites Web utilisent la technologie des cookies. Certains cookies sont utiles parce qu'ils permettent d'améliorer l'expérience de l'utilisateur. Les cookies accélèrent la vitesse de navigation dans notre site Web, retiennent des informations pour que vous n'ayez pas à les saisir à chaque fois que vous visitez notre site Web, nous aident à vous fournir du contenu personnalisé et nous permettent d'apprendre sur votre visite, entre autres.</p>
<p style="text-align: justify;"><strong><strong>2.3</strong></strong>&nbsp;Certains cookies que nous utilisons nécessitent votre consentement, tandis que d'autres sont exemptés.</p>
<ul>
    <li style="text-align: justify;"><strong><strong>Cookies exemptés de consentement</strong></strong>&nbsp;: les cookies strictement nécessaires garantissent des fonctions sans lesquelles on ne pourrait pas utiliser le site Web tel que prévu. Ils sont stockés sur votre ordinateur au cours de la session en cours du navigateur. Les cookies strictement nécessaires garantissent que, lorsque vous envoyez une requête pour les fonctionnalités d'un site web, on vous montre une version qui a une quantité de données en fonction de la largeur de bande correspondant à votre connexion Internet. Ces cookies garantissent également que, lorsque vous changez de page, la fonction de changement de HTTP à HTTPS ait lieu. Les cookies de ce type retiennent également votre décision concernant l'utilisation de cookies sur notre site Web. Votre consentement n'est pas requis pour les cookies strictement nécessaires.</li>
    <li style="text-align: justify;"><strong><strong>Cookies requérant consentement</strong></strong>&nbsp;: tous les autres cookies qui ne sont pas strictement nécessaires pour utiliser le site Web accomplissent toutefois des tâches importantes. Sans ces cookies, les fonctions destinées à votre commodité sur notre site, tel que vos paramètres personnels ou les fonctions de remplissage automatique, ne pourraient pas être conservées et devraient donc être réenregistrées sur chaque page.</li>
</ul>
<ol start="3">
    <li style="text-align: justify;"><strong><strong> TYPES DE COOKIES QUE Threedrenders&nbsp;UTILISE</strong></strong></li>
</ol>
<p style="text-align: justify;"><strong><strong>3.1</strong></strong>&nbsp;Notre site Web peut utiliser trois&nbsp;types de cookies&nbsp;: les cookies strictement nécessaires, les cookies de performance et les cookies fonctionnels.</p>
<ul>
    <li style="text-align: justify;"><strong><strong>Les cookies strictement nécessaires</strong></strong>&nbsp;sont essentiels afin de vous permettre de vous déplacer sur le site et d'utiliser ses fonctionnalités. Ces cookies temporaires ne durent que tant que votre navigateur est ouvert et sont utilisés à des fins techniques telles que pour permettre une meilleure navigation sur notre site Web. Sans ces cookies, les services que vous avez demandés ne pourraient pas être fournis&nbsp;; par exemple, se souvenir de vos actions antérieures (p. ex. un texte saisi) lorsque vous revenez à la page dans la même session. Une fois que vous fermez votre navigateur, le cookie disparaît.</li>
    <li style="text-align: justify;"><strong><strong>Les cookies de performance</strong></strong>&nbsp;sont stockés sur votre ordinateur pour de plus longues périodes et sont utilisés à des fins comme le suivi du nombre de visiteurs uniques sur notre site Web et pour d'autres informations telles que le nombre de fois qu'une page est visualisée, combien de temps un utilisateur passe sur une page, et d'autres statistiques Web pertinentes. Ces cookies ne retiennent point d'informations permettant d'identifier un utilisateur. Les informations recueillies sont regroupées, et donc rendues anonymes. Ces cookies sont utilisés uniquement pour améliorer la performance du site Web, et par conséquent l'expérience de l'utilisateur.</li>
    <li style="text-align: justify;"><strong><strong>Les cookies fonctionnels</strong></strong>&nbsp;permettent au site Web d'enregistrer les informations qui ont déjà été saisies (tel que les noms d'utilisateur, les choix de langue et l'emplacement) afin de pouvoir vous offrir des fonctions améliorées et personnalisées. Les cookies fonctionnels sont également utilisés pour activer les fonctionnalités que vous demandez, comme la lecture de vidéos. Ces cookies recueillent des informations anonymes et ne peuvent pas suivre vos déplacements sur d'autres sites Web.</li>
</ul>
<p style="text-align: justify;"><strong><strong>3.2 Cookies tiers</strong></strong>&nbsp;: nous pourrions utiliser des fournisseurs de services tiers pour nous aider à fournir certaines données statistiques et d'analyse d'informations. Par exemple, les cookies tiers sont utilisés pour mesurer la performance du site, les événements, et l'activité des visiteurs afin de garantir que le site Web réponde aux besoins des utilisateurs et nous aider à apporter des améliorations pour la navigation, la recherche et le contenu. Nous nous appuyons principalement sur Google Analytics pour cela. Consultez la section 4 ci-dessous pour plus de détails.<br></p>
<ol start="4">
    <li style="text-align: justify;"><strong><strong> GOOGLE ANALYTICS</strong></strong></li>
</ol>
<p style="text-align: justify;"><strong><strong>4.1</strong></strong>&nbsp;Nous utilisons Google Analytics, un service d'analyse d'informations Web fourni par Google Inc. («&nbsp;Google&nbsp;»). Google Analytics utilise des cookies, qui sont des fichiers de texte placés sur votre ordinateur, pour aider le site Internet à analyser comment les utilisateurs utilisent le site Web. Les informations générées par les cookies concernant votre utilisation du site Web seront transmises et stockées par Google sur des serveurs situés aux États-Unis. Google utilisera cette information pour notre compte comme opérateur du site Web dans le but d'évaluer votre utilisation du site Web, pour compiler des rapports sur l'activité du site pour les opérateurs du site Web et afin de leur fournir d'autres services relatifs à l'activité du site et à l'utilisation de l'Internet.</p>
<p style="text-align: justify;">Cependant, veuillez noter que si vous le faites, vous risquez de ne pas pouvoir utiliser toutes les fonctionnalités du site Web.</p>
<p style="text-align: justify;"><strong><strong>4.2</strong></strong>&nbsp;Vous pouvez aussi refuser d'être suivi par Google Analytics avec des effets futurs en téléchargeant et installant l'extension de navigateur de non-adhésion à Google Analytics pour votre navigateur Web actuel&nbsp;: (Cliquez ici&nbsp;<a href="https://tools.google.com/dlpage/gaoptout?hl=en-GB">https://tools.google.com/dlpage/gaoptout?hl=en-GB</a>).</p>
<ol start="5">
    <li style="text-align: justify;"><strong><strong> COMMENT CONTRÔLER ET DÉSACTIVER LES COOKIES</strong></strong></li>
</ol>
<p style="text-align: justify;"><strong><strong>5.1</strong></strong>&nbsp;Vous pouvez contrôler et/ou supprimer ou désactiver les cookies à tout moment en modifiant les paramètres de votre navigateur. Les navigateurs varient&nbsp;; veuillez consulter les instructions relatives à votre navigateur pour savoir plus sur les paramètres liés aux cookies et à la sécurité et la confidentialité qui peuvent être disponibles.</p>
<p style="text-align: justify;"><strong><strong>5.2</strong></strong>&nbsp;Vous devez pourtant savoir que si vous désactivez les cookies, vous pourriez ne pas être en mesure de tirer pleinement parti de toutes les fonctionnalités de notre site Web.</p>
<ol start="6">
    <li style="text-align: justify;"><strong><strong> PLUGINS DES RÉSEAUX SOCIAUX</strong></strong></li>
</ol>
<p style="text-align: justify;"><strong><strong>6.1</strong></strong>&nbsp;Notre site Web pourrait utiliser ce que l'on appelle les plugins sociaux («&nbsp;plugins&nbsp;») de réseaux sociaux comme Twitter, Facebook, YouTube, Pinterest, Instagram et Tumbler. Ces plugins sont signalés avec le logo respectif du réseau social. Lorsque vous accédez à notre site Web, votre navigateur établit une connexion directe avec les serveurs de ces réseaux sociaux. Le contenu du plugin est transmis par le réseau social directement à votre navigateur, qui l'intègre alors au site Web.</p>
<p style="text-align: justify;"><strong><strong>6.2</strong></strong>&nbsp;L'intégration du plugin fait que Facebook, par exemple, reçoive les informations que vous avez chargées de la page correspondante du site Web. Si vous êtes connecté à Facebook, cela permettra de mettre en rapport votre visite avec votre compte Facebook. Veuillez noter qu'un échange de ces informations existe déjà lorsque vous visitez notre site Web, que vous interagissiez avec le plugin ou pas. Si vous interagissez avec les plugins, par exemple en appuyant sur le bouton «&nbsp;J'aime&nbsp;», les informations correspondantes sont envoyées directement à Facebook par votre navigateur et y sont mémorisées. Vous pouvez trouver des informations sur l'objet et l'étendue de l'acquisition de données ainsi que sur la manière dont les données sont traitées et utilisées par les réseaux sociaux, vos droits et les paramètres facultatifs pour protéger votre sphère privée, dans les notes des réseaux sociaux relatives à la protection des données.</p>
<p style="text-align: justify;"><strong><strong>6.3</strong></strong>&nbsp;Si vous ne voulez pas que les réseaux sociaux incorporés recueillent des données vous concernant via notre site Web, vous devez vous déconnecter du domaine respectif du réseau social avant de visiter le site Web. Si vous souhaitez éviter que des informations soient échangées avec les réseaux sociaux pendant votre visite sur notre site Web, vous pouvez refuser les cookies à travers les paramètres de votre navigateur et d'autres outils.</p>
<ol start="7">
    <li style="text-align: justify;"><strong><strong> LES BALISES WEB</strong></strong></li>
</ol>
<p style="text-align: justify;"><strong><strong>7.1</strong></strong>&nbsp;Nous pourrions utiliser des balises web (également appelées «&nbsp;web bugs&nbsp;», «&nbsp;pixels tags&nbsp;» ou «&nbsp;clear GIFs&nbsp;») principalement pour recueillir et conserver des données agrégées (tels que le nombre de visiteurs) qui nous aideraient à voir quels sont les domaines les plus populaires auprès de nos utilisateurs et à améliorer et mettre à jour le contenu de notre site Web.</p>